### ISSUE TITLE
Editing being blocked

### ISSUE THREAD

**Issue by bitno** [coneda/kor#138]
Dear @moritzschepp 

Some entities seem to be blocked when trying to edit. 

`The entity has been edited meanwhile. Please find the new values below
`
But there is nothing below. Would you know, what could be causing this error? The log is just referring to `method_missing`. 

Could the current version pre2 be the issue?

Many thanks and kind regards,
Leo

**Comment by moritzschepp** [comment]
I'm not sure what you mean: The message tells you that

* you opened the form to edit this particular entity
* somebody else opened it
* somebody else saved it
* you tried to save it

In this situation, you would be overwriting the other user's data so KOR doesn't allow it.

When you say that "there is nothing below", does that mean that the form is not being shown? Can you give me more context about the `method_missing` log entry? Perhaps it is related.

**Comment by bitno** [comment]
I think I might be onto something. In my first import I used {} brackets in column "properties" instead of []. I wanted to fix the problem, my changing this and importing those again. But it won't let me.
Do you have any idea, how I could fix this problem? Because it is still not possible to edit those entities. Many thanks

This is the error I get in terminal:

```
kor@conedakor5:/var/www/rack/kor/current$ RAILS_ENV=production bundle exec bin/kor import -f excel tmp/excel_import_20171030
command: import
options: {:format=>"excel", :username=>"admin", :ignore_stale=>false, :obey_permissions=>false, :simulate=>false, :ignore_validations=>false, :collection_id=>[], :kind_id=>[], :verbose=>true}
file entities.0001.xls, row 2, entity id 460284: saving: {"attachment"=>[{"synonyms"=>[], "fields"=>{}, "properties"=>{}}, {"synonyms"=>[], "fields"=>{}, "properties"=>[{"label"=>"Blaue Markierung", "value"=>"\"44\""}]}], "comment"=>["", nil]}
bundler: failed to load command: bin/kor (bin/kor)
ActiveRecord::StaleObjectError: Attempted to update a stale object: Entity
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/locking/optimistic.rb:102:in `_update_record'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/attribute_methods/dirty.rb:129:in `_update_record'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/callbacks.rb:310:in `block in _update_record'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_update_callbacks'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/callbacks.rb:310:in `_update_record'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/timestamp.rb:70:in `_update_record'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/persistence.rb:504:in `create_or_update'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/callbacks.rb:302:in `block in create_or_update'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/callbacks.rb:302:in `create_or_update'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/persistence.rb:120:in `save'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/validations.rb:37:in `save'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/attribute_methods/dirty.rb:21:in `save'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:220:in `transaction'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:286:in `block in save'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:285:in `save'
  /var/www/rack/kor/releases/20171030120647/lib/kor/import/excel.rb:115:in `block (2 levels) in run'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/spreadsheet-1.0.3/lib/spreadsheet/worksheet.rb:147:in `block in each'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/spreadsheet-1.0.3/lib/spreadsheet/worksheet.rb:146:in `upto'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/spreadsheet-1.0.3/lib/spreadsheet/worksheet.rb:146:in `each'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/spreadsheet-1.0.3/lib/spreadsheet/excel/worksheet.rb:47:in `each'
  /var/www/rack/kor/releases/20171030120647/lib/kor/import/excel.rb:33:in `each_with_index'
  /var/www/rack/kor/releases/20171030120647/lib/kor/import/excel.rb:33:in `block in run'
  /var/www/rack/kor/releases/20171030120647/lib/kor/import/excel.rb:28:in `each'
  /var/www/rack/kor/releases/20171030120647/lib/kor/import/excel.rb:28:in `run'
  /var/www/rack/kor/releases/20171030120647/lib/kor/command_line.rb:113:in `run'
  bin/kor:11:in `<top (required)>'
```

**Comment by moritzschepp** [comment]
So if you know that the data you are importing is more correct than the one you are overwriting, there is a command line switch to ignore stale record errors. Run `bundle exec bin/kor import --help`  to see which one it is.

**Comment by bitno** [comment]
;-D
will add `-m` to the code. Just kidding, `-i` it is. I'm waiting for my colleagues to finish their day today, before I export and import again. Many thanks

**Comment by bitno** [comment]
Dear @moritzschepp 
This unfortunately didn't solve the issue, the error is still the same. I even tried -p and -o.
Any idea how this could be fixed? 
Many thanks, 
Leo

```
kor@conedakor5:/var/www/rack/kor/current$ RAILS_ENV=production bundle exec bin/kor import -f excel -i tmp/excel_import_20171031
command: import
options: {:format=>"excel", :username=>"admin", :ignore_stale=>true, :obey_permissions=>false, :simulate=>false, :ignore_validations=>false, :collection_id=>[], :kind_id=>[], :verbose=>true}
file entities.0002.xls, row 2, entity id 460284: saving: {"attachment"=>[{"synonyms"=>[], "fields"=>{}, "properties"=>{}}, {"synonyms"=>[], "fields"=>{}, "properties"=>[]}], "comment"=>["", nil]}
bundler: failed to load command: bin/kor (bin/kor)
ActiveRecord::StaleObjectError: Attempted to update a stale object: Entity
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/locking/optimistic.rb:102:in `_update_record'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/attribute_methods/dirty.rb:129:in `_update_record'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/callbacks.rb:310:in `block in _update_record'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_update_callbacks'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/callbacks.rb:310:in `_update_record'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/timestamp.rb:70:in `_update_record'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/persistence.rb:504:in `create_or_update'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/callbacks.rb:302:in `block in create_or_update'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:117:in `call'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:505:in `call'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/callbacks.rb:302:in `create_or_update'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/persistence.rb:120:in `save'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/validations.rb:37:in `save'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/attribute_methods/dirty.rb:21:in `save'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:286:in `block (2 levels) in save'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:220:in `transaction'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:286:in `block in save'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.6/lib/active_record/transactions.rb:285:in `save'
  /var/www/rack/kor/releases/20171030120647/lib/kor/import/excel.rb:115:in `block (2 levels) in run'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/spreadsheet-1.0.3/lib/spreadsheet/worksheet.rb:147:in `block in each'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/spreadsheet-1.0.3/lib/spreadsheet/worksheet.rb:146:in `upto'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/spreadsheet-1.0.3/lib/spreadsheet/worksheet.rb:146:in `each'
  /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/spreadsheet-1.0.3/lib/spreadsheet/excel/worksheet.rb:47:in `each'
  /var/www/rack/kor/releases/20171030120647/lib/kor/import/excel.rb:33:in `each_with_index'
  /var/www/rack/kor/releases/20171030120647/lib/kor/import/excel.rb:33:in `block in run'
  /var/www/rack/kor/releases/20171030120647/lib/kor/import/excel.rb:28:in `each'
  /var/www/rack/kor/releases/20171030120647/lib/kor/import/excel.rb:28:in `run'
  /var/www/rack/kor/releases/20171030120647/lib/kor/command_line.rb:113:in `run'
  bin/kor:11:in `<top (required)>'
```

**Comment by moritzschepp** [comment]
Can you send me `entities.0002.xls` via mail or post it here?

**Comment by bitno** [comment]
Sure, here you go. 
[entities.0002.xls.zip](https://github.com/coneda/kor/files/1434355/entities.0002.xls.zip)

**Comment by moritzschepp** [comment]
Great! I see the problem now. There was a bug in the deactivation of stale checking. Please use the current master where this is fixed or copy the file `lib/kor/import/excel.rb` from master to your installation and try the import with `-i` again.

**Comment by bitno** [comment]
Will do asap, many thanks as always!
