### ISSUE TITLE
after deployment to v.2.1.0 ruby scripts not working

### ISSUE THREAD

**Issue by bitno** [coneda/kor#140]
Dear Moritz,
I've upgraded our KOR5 instance to v.2.1.0 and since the update I'm not able to use ruby scripts anymore. There seems to be an issue with the environment. Can you please help?

```
kor@conedakor5:/var/www/rack/kor/current$ RAILS_ENV=production bundle exec ruby /var/www/rack/kor/shared/scripts/import_bildnachweis.rb 
/var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:263:in `const_get': uninitialized constant Rack::Cors (NameError)
	from /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:263:in `block in constantize'
	from /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `each'
	from /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `inject'
	from /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.6/lib/active_support/inflector/methods.rb:259:in `constantize'
	from /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/stack.rb:24:in `klass'
	from /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/stack.rb:43:in `build'
	from /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/stack.rb:118:in `block in build'
	from /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/stack.rb:118:in `each'
	from /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/stack.rb:118:in `inject'
	from /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/stack.rb:118:in `build'
	from /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/engine.rb:502:in `app'
	from /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application/finisher.rb:34:in `block in <module:Finisher>'
	from /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
	from /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
	from /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /opt/rbenv/versions/2.2.5/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /opt/rbenv/versions/2.2.5/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /opt/rbenv/versions/2.2.5/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /opt/rbenv/versions/2.2.5/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /opt/rbenv/versions/2.2.5/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /opt/rbenv/versions/2.2.5/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /opt/rbenv/versions/2.2.5/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /opt/rbenv/versions/2.2.5/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /opt/rbenv/versions/2.2.5/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
	from /var/www/rack/kor/shared/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
	from /var/www/rack/kor/current/config/environment.rb:5:in `<top (required)>'
	from /var/www/rack/kor/shared/scripts/import_bildnachweis.rb:4:in `require'
	from /var/www/rack/kor/shared/scripts/import_bildnachweis.rb:4:in `<main>'
```

![bildschirmfoto 2017-10-30 um 14 48 17](https://user-images.githubusercontent.com/15378927/32174465-3ab31f2e-bd82-11e7-86a5-979debf2084e.png)

**Comment by moritzschepp** [comment]
I agree, seems like an environment problem. Are you in the correct directory with your prompt? After deploying (which changes the `current` symlink), you should go back to `/var/www/rack/kor` and re-enter the current directory.

**Comment by bitno** [comment]
Jep, once again your were right. I tried it again now from home and it worked fine after installing bundle.
Many thanks as always!
```
Could not find rake-12.0.0 in any of the sources
Run `bundle install` to install missing gems.
```

**Comment by moritzschepp** [comment]
strange though, I would have expected the error message to say that but it essentially complains about a missing gem ...
